-- Sesion 33 (deploy v1.1.0-qas): snapshot de las 729 asignaciones
-- usuario_roles de DES, portado via (username, codigo_rol) para que
-- funcione en cualquier ambiente donde existan esos usuarios + roles.
--
-- Idempotente: ON CONFLICT (usuario_id, rol_id) DO NOTHING sobre la PK.
-- Si un usuario o rol no existe, la fila se ignora silenciosamente.
-- Generado: 729 asignaciones.

INSERT INTO usuario_roles (usuario_id, rol_id)
SELECT u.id, r.id
FROM (VALUES
    ($$aadriazola$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aaguilar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aalarcon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aaranibar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aarce$$, $$ELABORADOR - REVISOR$$),
    ($$abasswerner$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$abeltran$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$acahuana$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$achambi$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$acoca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$acondori$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$acossio$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$acuestas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$admin$$, $$ADMIN$$),
    ($$admin_local$$, $$ADMIN$$),
    ($$aemorice$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aescobar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aespinoza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aflores$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$afloresh$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$agarcia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$agranier$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$agutierrezm$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ajacome$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ajurado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$alazaro$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$alima$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$alimam$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$alimpias$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$alinares$$, $$ELABORADOR - REVISOR$$),
    ($$alinarest$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$amayorga$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$amercado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$amiranda$$, $$ELABORADOR - REVISOR$$),
    ($$amolina$$, $$ELABORADOR - REVISOR$$),
    ($$amontano$$, $$ELABORADOR - REVISOR$$),
    ($$anoya$$, $$ELABORADOR - REVISOR$$),
    ($$aorihuela$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aoropeza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aparedes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$aparedesa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$apaz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$apinto$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$apool$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$arios$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$arodriguez$$, $$ELABORADOR - REVISOR$$),
    ($$aromero$$, $$ETO$$),
    ($$aruiz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asaavedra$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asalazar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asalazarm$$, $$ELABORADOR - REVISOR$$),
    ($$asalinas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asalvatierra$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asanchez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asaucedo$$, $$ELABORADOR - REVISOR$$),
    ($$asegura$$, $$ELABORADOR - REVISOR$$),
    ($$aserrano$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asinani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asosa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$asotopolar$$, $$ELABORADOR - REVISOR$$),
    ($$aticona$$, $$ELABORADOR - REVISOR$$),
    ($$atordoya$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$atorrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$atorricor$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$avallejos$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$avargas$$, $$ELABORADOR - REVISOR$$),
    ($$baguilard$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$balfaro$$, $$ELABORADOR - REVISOR$$),
    ($$bapaza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$bconde$$, $$ELABORADOR - REVISOR$$),
    ($$bgutierrezq$$, $$ELABORADOR - REVISOR$$),
    ($$bhuanverdy$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$bquisbert$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$bribera$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$bsilva$$, $$ELABORADOR - REVISOR$$),
    ($$bteran$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$bterrazas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$btola$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$bzenteno$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$calfaro$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$carispe$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cbanegas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cbeltran$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ccanseco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ccardona$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ccastro$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ccolquechambi$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ccondori$$, $$ELABORADOR - REVISOR$$),
    ($$ccrespo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ccuba$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ccuellar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cdacosta$$, $$ELABORADOR - REVISOR$$),
    ($$cescobar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cespinoza$$, $$ETO$$),
    ($$cestivariz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cestrada$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cgarciag$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cgarfias$$, $$ELABORADOR - REVISOR$$),
    ($$cgutierrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cjimenez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cjove$$, $$ELABORADOR - REVISOR$$),
    ($$cjustiniano$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$clopez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$clopezm$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$clopezv$$, $$ELABORADOR - REVISOR$$),
    ($$cmaldonado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cmarquez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cmartinez$$, $$ELABORADOR - REVISOR$$),
    ($$cmartinezp$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cmier$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cnavia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cpaco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cpecka$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cperedo$$, $$ELABORADOR - REVISOR$$),
    ($$cperez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cpiluy$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cquisbert$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$creynozo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$crios$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$criosa$$, $$ELABORADOR - REVISOR$$),
    ($$crodas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$crodriguez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$crodriguezc$$, $$ELABORADOR - REVISOR$$),
    ($$crojas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$csalazarv$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$csoria$$, $$ELABORADOR - REVISOR$$),
    ($$ctavera$$, $$ELABORADOR - REVISOR$$),
    ($$ctuco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cvaca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$cvelasquez$$, $$ELABORADOR - REVISOR$$),
    ($$cvillegas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$daracayo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$daramayo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dayllon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dbazbazat$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dberdeja$$, $$ELABORADOR - REVISOR$$),
    ($$dbigabriel$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dblanco$$, $$ELABORADOR - REVISOR$$),
    ($$dcallisaya$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dcanaviri$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dcardenas$$, $$ELABORADOR - REVISOR$$),
    ($$dcartagena$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dchoqueticlla$$, $$ELABORADOR - REVISOR$$),
    ($$dcordova$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dcossio$$, $$ELABORADOR - REVISOR$$),
    ($$dcuellar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dcusi$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ddias$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$descalante$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$destrada$$, $$ELABORADOR - REVISOR$$),
    ($$dguachalla$$, $$ELABORADOR - REVISOR$$),
    ($$dgutierrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$disnado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$djimenez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dlazarte$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dleandro$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dledezma$$, $$ELABORADOR - REVISOR$$),
    ($$dloza$$, $$ELABORADOR - REVISOR$$),
    ($$dmachaca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dmillares$$, $$ELABORADOR - REVISOR$$),
    ($$dmiranda$$, $$ELABORADOR - REVISOR$$),
    ($$dmorales$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dpereira$$, $$ELABORADOR - REVISOR$$),
    ($$dsaavedra$$, $$ELABORADOR - REVISOR$$),
    ($$dsanjinez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dsejas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dsirpa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dsolizs$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dsucasaca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dtarqui$$, $$ELABORADOR - REVISOR$$),
    ($$dtoconas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$dtorrez$$, $$ELABORADOR - REVISOR$$),
    ($$dvaca$$, $$ELABORADOR - REVISOR$$),
    ($$dzapana$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ealberto$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$eaquice$$, $$ELABORADOR - REVISOR$$),
    ($$earce$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$eardaya$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$eavila$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ebejar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ecaceres$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ecamargo$$, $$ELABORADOR - REVISOR$$),
    ($$ecarrillo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$echipana$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ecuellar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$eduran$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$eflores$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$egarnica$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$egarrido$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ejarandilla$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ejemio$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ekanan$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$elaborador_revisor$$, $$ELABORADOR - REVISOR$$),
    ($$elaborador_revisor_aprobador$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$elopez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$elorono$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$eluna$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$emolina$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$enina$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$epereira$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$equinajo$$, $$ELABORADOR - REVISOR$$),
    ($$equispe$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$erada$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$erivero$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$erodriguez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$esuxo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$eto_test$$, $$ETO$$),
    ($$evaldez$$, $$ELABORADOR - REVISOR$$),
    ($$evargas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$evargase$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$evera$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$falvarez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fbadani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fcamacho$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fcamachom$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fcartagena$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fchino$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fchipana$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fconde$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fcopa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fcortez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fflores$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fgutierrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fhinojosa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fjerez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$flopez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fmamani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fmamanim$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fmarquez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fmejia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fmerino$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fonofre$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$frequena$$, $$ELABORADOR - REVISOR$$),
    ($$fsantalla$$, $$ELABORADOR - REVISOR$$),
    ($$fsilva$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fticona$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fvargas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fyujra$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fyujrag$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$fyujrai$$, $$ELABORADOR - REVISOR$$),
    ($$gacosta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$galbarracin$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$galcocer$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$galcon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gbaradi$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gbascon$$, $$ELABORADOR - REVISOR$$),
    ($$gcabrera$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gcalcina$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gcapriles$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gcarvajal$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gescobar$$, $$ELABORADOR - REVISOR$$),
    ($$gescobari$$, $$ELABORADOR - REVISOR$$),
    ($$ggalvan$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ggonzales$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ggorostiaga$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ggutierrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ghuanca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gignacio$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gjemio$$, $$ELABORADOR - REVISOR$$),
    ($$gjimenez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$glaura$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gmallea$$, $$ELABORADOR - REVISOR$$),
    ($$gmamani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gmayori$$, $$ELABORADOR - REVISOR$$),
    ($$gmendieta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gmendoza$$, $$ELABORADOR - REVISOR$$),
    ($$grevollo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$grioja$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$grodriguez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$grojas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$grojasl$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gsanca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gtancaram$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gvalle$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gvargas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gvasquez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gvegaa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gvela$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gvillegas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$gviscarra$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$haguilera$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$hcastillo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$hcastro$$, $$ELABORADOR - REVISOR$$),
    ($$hgamez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$hgranadero$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$hmamani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$hmercado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$hzambrana$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$iacosta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$iaguilar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$iari$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ibustamante$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$icanqui$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$icervantes$$, $$ELABORADOR - REVISOR$$),
    ($$icusicanqui$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ielio$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$iespinoza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$imarca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$imarquez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$imorales$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$isoruco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$itinta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$iverastegui$$, $$ELABORADOR - REVISOR$$),
    ($$ividaurre$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ivillca$$, $$ELABORADOR - REVISOR$$),
    ($$jacarapi$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jadministrativo$$, $$ELABORADOR - REVISOR$$),
    ($$jajata$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jarancibia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jaranibar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jarauz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jaruquipa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jbalcazar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jbarrancos$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jbecerra$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jbecerrai$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jburgos$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jcallejas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jcanisaca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jchoqueb$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jcolodro$$, $$ELABORADOR - REVISOR$$),
    ($$jcondoric$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jcondorif$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jcorzon$$, $$ELABORADOR - REVISOR$$),
    ($$jcruz$$, $$ELABORADOR - REVISOR$$),
    ($$jdiaz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jdiazl$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jeguez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jencina$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jencinas$$, $$ELABORADOR - REVISOR$$),
    ($$jespinozao$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jfranco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jfuentes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jgamboa$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$jgarcia$$, $$ELABORADOR - REVISOR$$),
    ($$jgarciaz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jgonzalesf$$, $$ELABORADOR - REVISOR$$),
    ($$jgonzalesg$$, $$ELABORADOR - REVISOR$$),
    ($$jgumucio$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jherbas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jhernani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jhurtadom$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jibarra$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jkaliman$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jkantuta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jllusco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jlopezf$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmachaca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmamani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmarin$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmendez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmercadog$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmillan$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmontecinos$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmonzon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmoreno$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jmurguia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jnava$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jnina$$, $$ELABORADOR - REVISOR$$),
    ($$jpaco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jpoma$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jquenta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jquispe$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jquispec$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jrada$$, $$ELABORADOR - REVISOR$$),
    ($$jrico$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jromano$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jrubindecelis$$, $$ELABORADOR - REVISOR$$),
    ($$jsanjines$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$jsoleto$$, $$ELABORADOR - REVISOR$$),
    ($$jtorrezm$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jtorricov$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jverastegui$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jvillaverde$$, $$ELABORADOR - REVISOR$$),
    ($$jvmamani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$jzurita$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kandrade$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$karias$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kayala$$, $$ELABORADOR - REVISOR$$),
    ($$kcastaneta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kcastellon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kclaure$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kgalarza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kgarvizu$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kibanez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kmendieta$$, $$ELABORADOR - REVISOR$$),
    ($$ksalazar$$, $$ELABORADOR - REVISOR$$),
    ($$kvillarroel$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$kzuazo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lalave$$, $$ELABORADOR - REVISOR$$),
    ($$lalvarez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lameller$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$larnez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$layala$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lballon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lbarrientos$$, $$ELABORADOR - REVISOR$$),
    ($$lbetancourt$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lburton$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lcampos$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lcandia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lcardona$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lcatacora$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lchoque$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lclaudio$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lcondori$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lcondorit$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lcuili$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ldelafuente$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lescobar$$, $$ELABORADOR - REVISOR$$),
    ($$lespinoza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lgonzales$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lhurtado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ljimenez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$llaura$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lledezma$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$llimachi$$, $$ELABORADOR - REVISOR$$),
    ($$lmamani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lmiranda$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lmurga$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lorellana$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lpazsoldan$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lpena$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lquispe$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lrada$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lramirez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lroca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lrodriguezm$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lsalinas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lsalinasc$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lsalinasv$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lsanchez$$, $$ELABORADOR - REVISOR$$),
    ($$lsirpa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ltellez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lvaras$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lvargas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lvargasg$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lvargass$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lvelasco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lvilla$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$lvinolas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$maduran$$, $$ELABORADOR - REVISOR$$),
    ($$maguilarj$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$malban$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$malcon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mandrade$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mapaza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$marce$$, $$ELABORADOR - REVISOR$$),
    ($$maro$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$mbacarreza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mbravo$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$mcaballero$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mcallisaya$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mcamacho$$, $$ELABORADOR - REVISOR$$),
    ($$mcanaza$$, $$ELABORADOR - REVISOR$$),
    ($$mcarvajalq$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mcassas$$, $$ELABORADOR - REVISOR$$),
    ($$mcastedo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mcastedoz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mcazuriaga$$, $$ELABORADOR - REVISOR$$),
    ($$mchura$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mcochi$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mecanaviri$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mencinas$$, $$ELABORADOR - REVISOR$$),
    ($$mergueta$$, $$ELABORADOR - REVISOR$$),
    ($$mfita$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mflores$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mfloresb$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mfloreso$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mfloresp$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mgalarza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mguarachi$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mguaygua$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mgutierrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mgutierrezc$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mhegedus$$, $$ELABORADOR - REVISOR$$),
    ($$mherrera$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mhuallpa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mhuchani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mhurtado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mibanez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mledezma$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mleonz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mloayza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mlozac$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mluna$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mmaldonadom$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mmamanif$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mmamaniq$$, $$ELABORADOR - REVISOR$$),
    ($$mmanotas$$, $$ELABORADOR - REVISOR$$),
    ($$mmarca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mmayta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mmedrano$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mmendozac$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mmhur$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mmichel$$, $$ELABORADOR - REVISOR$$),
    ($$mmorales$$, $$ELABORADOR - REVISOR$$),
    ($$mmunoz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$morihuela$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mortizp$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mpachagaya$$, $$ELABORADOR - REVISOR$$),
    ($$mpaiva$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mparedes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mpenaranda$$, $$ELABORADOR - REVISOR$$),
    ($$mperalta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mpereira$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mpol$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mpoma$$, $$ELABORADOR - REVISOR$$),
    ($$mponces$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mquezadas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mquino$$, $$ELABORADOR - REVISOR$$),
    ($$mquispe$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mquispez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mrodriguezm$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mrojas$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$mrojasm$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$msanchez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$msancheza$$, $$ELABORADOR - REVISOR$$),
    ($$msaucedo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mthuanca$$, $$ELABORADOR - REVISOR$$),
    ($$mtorrez$$, $$ELABORADOR - REVISOR$$),
    ($$mtouchard$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mugarte$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mvargasq$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$mvillarreal$$, $$ELABORADOR - REVISOR$$),
    ($$mzurita$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$naguilar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nalanes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$narosqueta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nbonilla$$, $$ELABORADOR - REVISOR$$),
    ($$ncaceres$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ncharca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nchavez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ncrespo$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$nduran$$, $$ELABORADOR - REVISOR$$),
    ($$ngisbert$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$nimanareco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nmoreno$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nperez$$, $$ELABORADOR - REVISOR$$),
    ($$nquisbert$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nroca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nrojas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ntarifa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ntorrico$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nvargas$$, $$ELABORADOR - REVISOR$$),
    ($$nvedia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$nyevara$$, $$ELABORADOR - REVISOR$$),
    ($$nzamorano$$, $$ELABORADOR - REVISOR$$),
    ($$oaltamirano$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ochoque$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ococa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ocolmena$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$oguzman$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$omurillo$$, $$ELABORADOR - REVISOR$$),
    ($$opoma$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pabapinta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pabrego$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pardiles$$, $$ELABORADOR - REVISOR$$),
    ($$pargollo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pazurduy$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pbazan$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pcastellon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pcedeno$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pcerda$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pchoque$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pcordero$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pcriales$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pdiaz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pguzman$$, $$ELABORADOR - REVISOR$$),
    ($$phurtado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pjurado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pmaceda$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pmercado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$promotor$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$psuarez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$purquiola$$, $$ELABORADOR - REVISOR$$),
    ($$puyuni$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pvillca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$pvillegas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$qgomez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$raguilar$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rantezana$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rarias$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rcalderon$$, $$ELABORADOR - REVISOR$$),
    ($$rcallisaya$$, $$ELABORADOR - REVISOR$$),
    ($$rcampero$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rchalco$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rcoca$$, $$ELABORADOR - REVISOR$$),
    ($$rconde$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rcontreras$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rcruz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rflores$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rgutierrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rgutierrezs$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rguzmanm$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rillanes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rlima$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rlimachi$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rlimachiq$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rlira$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rlopez$$, $$ELABORADOR - REVISOR$$),
    ($$rluna$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rmamani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rmamania$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rmendoza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rmontecinos$$, $$ELABORADOR - REVISOR$$),
    ($$rmontes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rmontiel$$, $$ELABORADOR - REVISOR$$),
    ($$rmoya$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rmurillo$$, $$ELABORADOR - REVISOR$$),
    ($$rnavarro$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rpadilla$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rparedes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rpaz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rpenaloza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rpenaranda$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rperalta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rperaltal$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rperez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rquinteros$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rquirogat$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rramos$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rrivera$$, $$ELABORADOR - REVISOR$$),
    ($$rrojas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rsantamaria$$, $$ELABORADOR - REVISOR$$),
    ($$rsantos$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rsoto$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rtaborga$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rtancara$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rterrazas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rtinta$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rtorrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rvaca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rvacas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rvalverde$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rvargasr$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rvenegas$$, $$ELABORADOR - REVISOR$$),
    ($$rvillarroel$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rvillaverde$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$rzapana$$, $$ELABORADOR - REVISOR$$),
    ($$sachacollo$$, $$ELABORADOR - REVISOR$$),
    ($$sadministrativo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$salfaro$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$samonzabel$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sanez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sarenas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sarmijo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sbaldiviezo$$, $$ELABORADOR - REVISOR$$),
    ($$sbarrera$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sblanco$$, $$ELABORADOR - REVISOR$$),
    ($$scalani$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$schaparro$$, $$ELABORADOR - REVISOR$$),
    ($$scoronado$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sgarcia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sgautam$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sguaygua$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sleyva$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$slujan$$, $$ELABORADOR - REVISOR$$),
    ($$smamani$$, $$ELABORADOR - REVISOR$$),
    ($$smariscal$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$smaydana$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$smichel$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$solicitante$$, $$ELABORADOR - REVISOR - APROBADOR$$),
    ($$spenaloza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sprocchio$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$squispea$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$srada$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sreyes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sriveros$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$starquiola$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$sterceros$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$stola$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$stroncoso$$, $$ELABORADOR - REVISOR$$),
    ($$svalencia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$svillarroel$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$talarcon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$tchura$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$tflorian$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$theredia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$tluna$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$tmendoza$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$tnunez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$tsuntura$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$tvelasco$$, $$ELABORADOR - REVISOR$$),
    ($$vcalderon$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vcondori$$, $$ELABORADOR - REVISOR$$),
    ($$vcortez$$, $$ELABORADOR - REVISOR$$),
    ($$vflores$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vgarcia$$, $$ELABORADOR - REVISOR$$),
    ($$vgutierrez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vibanez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$villescas$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$visualizador$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$visualizador_cl$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vjimenez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vjustinianoj$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vloayza$$, $$ELABORADOR - REVISOR$$),
    ($$vmamani$$, $$ELABORADOR - REVISOR$$),
    ($$vmartinez$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vmedina$$, $$ELABORADOR - REVISOR$$),
    ($$vmoscoso$$, $$ELABORADOR - REVISOR$$),
    ($$vortega$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vpenaranda$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vsaravia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vsiles$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vucedo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vvargasp$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$vvillarroelc$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$wacero$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$walanes$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$wcastillo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$wchoque$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$wchumacero$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$wcopa$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$wherrera$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$wmedina$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$wrojas$$, $$ELABORADOR - REVISOR$$),
    ($$wsalvatierra$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ycastro$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ychavez$$, $$ADMIN$$),
    ($$ychung$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$ypaz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$yperedo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$yrodriguez$$, $$ELABORADOR - REVISOR$$),
    ($$yschwarz$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$yvaca$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$yyujra$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$zchuquimia$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$zperedo$$, $$VISUALIZADOR (CL-EVAL)$$),
    ($$zyapura$$, $$VISUALIZADOR (CL-EVAL)$$)
) AS v(username, codigo)
JOIN usuarios u ON u.username = v.username
JOIN roles r ON r.codigo::text = v.codigo
ON CONFLICT (usuario_id, rol_id) DO NOTHING;
