"""002_add_ad_info_to_usuarios

Revision ID: bcf168a908fb
Revises: 900f8f678e10
Create Date: 2026-06-14 22:45:00.414331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf168a908fb'
down_revision: Union[str, None] = '900f8f678e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ad_info', sa.String(length=2000), nullable=True))
    op.add_column('usuarios', sa.Column('ad_postal_code', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('ad_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ad_last_synced_at')
    op.drop_column('usuarios', 'ad_postal_code')
    op.drop_column('usuarios', 'ad_info')
    # ### end Alembic commands ###
