"""add feriados table

Revision ID: 8e5eca60fc49
Revises: 44a351959c47
Create Date: 2026-06-15 21:30:41.383328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5eca60fc49'
down_revision: Union[str, None] = '44a351959c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('NACIONAL', 'DEPARTAMENTAL', 'EMPRESARIAL', name='tipo_feriado'), nullable=False),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feriados_departamento'), 'feriados', ['departamento'], unique=False)
    op.create_index(op.f('ix_feriados_fecha'), 'feriados', ['fecha'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feriados_fecha'), table_name='feriados')
    op.drop_index(op.f('ix_feriados_departamento'), table_name='feriados')
    op.drop_table('feriados')
    # ### end Alembic commands ###
