"""add email_templates table

Revision ID: f3aaec046492
Revises: 8e5eca60fc49
Create Date: 2026-06-15 21:35:36.000301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3aaec046492'
down_revision: Union[str, None] = '8e5eca60fc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Enum('NUEVA_TAREA', 'ALERTA_VENCIMIENTO', 'DOCUMENTO_APROBADO', 'DOCUMENTO_OBSERVADO', 'EVALUACION_PENDIENTE', 'AUTO_DELEGACION_ACTIVADA', name='codigo_plantilla'), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('asunto', sa.String(length=500), nullable=False),
    sa.Column('cuerpo_html', sa.Text(), nullable=False),
    sa.Column('variables_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_codigo'), 'email_templates', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_codigo'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
