"""add_audit_log_table

Revision ID: 1b5d968cb61c
Revises: 46f051137d34
Create Date: 2026-06-15 22:21:26.841425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b5d968cb61c'
down_revision: Union[str, None] = '46f051137d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_username', sa.String(length=80), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=200), nullable=True),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('recurso', sa.String(length=80), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('detalles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_accion'), 'audit_log', ['accion'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_exitoso'), 'audit_log', ['exitoso'], unique=False)
    op.create_index(op.f('ix_audit_log_recurso'), 'audit_log', ['recurso'], unique=False)
    op.create_index('ix_audit_log_recurso_created', 'audit_log', ['recurso', 'created_at'], unique=False)
    op.create_index('ix_audit_log_usuario_created', 'audit_log', ['usuario_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_usuario_id'), 'audit_log', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_usuario_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_usuario_created', table_name='audit_log')
    op.drop_index('ix_audit_log_recurso_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_recurso'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_exitoso'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_accion'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
