"""add tipos_documento table

Revision ID: ce84794abf90
Revises: 9e74402bced4
Create Date: 2026-06-15 21:49:34.031211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce84794abf90'
down_revision: Union[str, None] = '9e74402bced4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo_doc', sa.Integer(), nullable=False),
    sa.Column('periodo_vigencia', sa.Integer(), nullable=True),
    sa.Column('indefinido', sa.Boolean(), nullable=False),
    sa.Column('max_descargas_dia', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_documento_codigo'), 'tipos_documento', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_documento_codigo_doc'), 'tipos_documento', ['codigo_doc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_documento_codigo_doc'), table_name='tipos_documento')
    op.drop_index(op.f('ix_tipos_documento_codigo'), table_name='tipos_documento')
    op.drop_table('tipos_documento')
    # ### end Alembic commands ###
