"""add matriz_enrutamiento_eto table

Revision ID: 9e74402bced4
Revises: f3aaec046492
Create Date: 2026-06-15 21:41:23.350806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e74402bced4'
down_revision: Union[str, None] = 'f3aaec046492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriz_enrutamiento_eto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gerencia_id', sa.Integer(), nullable=False),
    sa.Column('analista_usuario_id', sa.Integer(), nullable=False),
    sa.Column('disponibilidad', sa.Enum('DISPONIBLE', 'AUSENTE', 'LICENCIA', name='disponibilidad_eto'), nullable=False),
    sa.Column('delegado_usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analista_usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delegado_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gerencia_id'], ['gerencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matriz_enrutamiento_eto_gerencia_id'), 'matriz_enrutamiento_eto', ['gerencia_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matriz_enrutamiento_eto_gerencia_id'), table_name='matriz_enrutamiento_eto')
    op.drop_table('matriz_enrutamiento_eto')
    # ### end Alembic commands ###
