"""add configuracion_global table

Revision ID: 44a351959c47
Revises: bcf168a908fb
Create Date: 2026-06-15 21:24:23.173817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a351959c47'
down_revision: Union[str, None] = 'bcf168a908fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_global',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('INT', 'FLOAT', 'BOOL', 'STR', 'JSON', name='tipo_configuracion'), nullable=False),
    sa.Column('categoria', sa.Enum('VIGENCIA', 'FLUJO', 'SEMAFORO', 'ARCHIVOS', 'DESCARGAS', 'GENERAL', name='categoria_configuracion'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('clave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion_global')
    # ### end Alembic commands ###
