"""add estados table

Revision ID: 46f051137d34
Revises: ce84794abf90
Create Date: 2026-06-15 21:53:26.763856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f051137d34'
down_revision: Union[str, None] = 'ce84794abf90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('contexto', sa.Enum('PROCESO', 'TAREA', 'AMBOS', name='contexto_estado'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_codigo'), 'estados', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estados_codigo'), table_name='estados')
    op.drop_table('estados')
    # ### end Alembic commands ###
