"""fix_B1_areas_unique_compound

Revision ID: b397cd9bfb91
Revises: 1b5d968cb61c
Create Date: 2026-06-15 22:35:21.025527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b397cd9bfb91'
down_revision: Union[str, None] = '1b5d968cb61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_areas_sigla'), table_name='areas')
    op.create_index(op.f('ix_areas_sigla'), 'areas', ['sigla'], unique=False)
    op.create_unique_constraint('uq_areas_gerencia_sigla', 'areas', ['gerencia_id', 'sigla'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_areas_gerencia_sigla', 'areas', type_='unique')
    op.drop_index(op.f('ix_areas_sigla'), table_name='areas')
    op.create_index(op.f('ix_areas_sigla'), 'areas', ['sigla'], unique=True)
    # ### end Alembic commands ###
