"""add documentos documento_flujo archivos_adjuntos

Revision ID: b88801d59687
Revises: 6451593bcab5
Create Date: 2026-06-17 10:23:18.040378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b88801d59687'
down_revision: Union[str, None] = '6451593bcab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gerencia_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=True),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('correlativo', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=2), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('aprobacion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expira_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vigencia', sa.Enum('VIGENTE', 'POR_VENCER', 'VENCIDO', 'OBSOLETO', name='vigencia_documento'), nullable=False),
    sa.Column('estatus', sa.Enum('EN_ELABORACION', 'EN_REVISION', 'APROBADO', 'OBSOLETO', name='estatus_documento'), nullable=False),
    sa.Column('codigo_antiguo', sa.String(length=50), nullable=True),
    sa.Column('comentarios_eto', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(vigencia <> 'VENCIDO') OR (estatus IN ('APROBADO', 'OBSOLETO'))", name='ck_documento_vencido_aprobado'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gerencia_id'], ['gerencias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'tipo_documento_id', 'correlativo', name='uq_documento_area_tipo_correlativo'),
    sa.UniqueConstraint('codigo', 'version', name='uq_documento_codigo_version')
    )
    op.create_index('ix_documento_area_tipo', 'documentos', ['area_id', 'tipo_documento_id'], unique=False)
    op.create_index('ix_documento_estatus_activo', 'documentos', ['estatus', 'activo'], unique=False)
    op.create_index('ix_documento_vigencia_expira', 'documentos', ['vigencia', 'expira_at'], unique=False)
    op.create_index(op.f('ix_documentos_activo'), 'documentos', ['activo'], unique=False)
    op.create_index(op.f('ix_documentos_aprobacion_at'), 'documentos', ['aprobacion_at'], unique=False)
    op.create_index(op.f('ix_documentos_area_id'), 'documentos', ['area_id'], unique=False)
    op.create_index(op.f('ix_documentos_codigo'), 'documentos', ['codigo'], unique=False)
    op.create_index(op.f('ix_documentos_codigo_antiguo'), 'documentos', ['codigo_antiguo'], unique=False)
    op.create_index(op.f('ix_documentos_estatus'), 'documentos', ['estatus'], unique=False)
    op.create_index(op.f('ix_documentos_expira_at'), 'documentos', ['expira_at'], unique=False)
    op.create_index(op.f('ix_documentos_gerencia_id'), 'documentos', ['gerencia_id'], unique=False)
    op.create_index(op.f('ix_documentos_proceso_id'), 'documentos', ['proceso_id'], unique=False)
    op.create_index(op.f('ix_documentos_tipo_documento_id'), 'documentos', ['tipo_documento_id'], unique=False)
    op.create_index(op.f('ix_documentos_vigencia'), 'documentos', ['vigencia'], unique=False)
    op.create_table('archivos_adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('nombre_storage', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('tipo_adjunto', sa.Enum('PRINCIPAL', 'FORMULARIO', name='tipo_adjunto'), nullable=False),
    sa.Column('storage_backend', sa.Enum('LOCAL', 'SHAREPOINT', name='storage_backend_adjunto'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_archivo_documento_tipo', 'archivos_adjuntos', ['documento_id', 'tipo_adjunto'], unique=False)
    op.create_index(op.f('ix_archivos_adjuntos_documento_id'), 'archivos_adjuntos', ['documento_id'], unique=False)
    op.create_table('documento_flujo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('estado_actual_id', sa.Integer(), nullable=False),
    sa.Column('tipo_solicitud', sa.Enum('CREACION', 'ACTUALIZACION', name='tipo_solicitud'), nullable=False),
    sa.Column('gerencia_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('codigo_snapshot', sa.String(length=20), nullable=False),
    sa.Column('version_snapshot', sa.String(length=2), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('elaborador_id', sa.Integer(), nullable=True),
    sa.Column('cargo_elaborador', sa.String(length=100), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('tiempo_vigencia_anos', sa.Integer(), nullable=True),
    sa.Column('requiere_evaluacion', sa.Boolean(), nullable=False),
    sa.Column('requiere_control_lectura', sa.Boolean(), nullable=False),
    sa.Column('alcance_difusion_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('revisor_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('aprobador_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reemplaza_documento_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('firma_usuario_id', sa.Integer(), nullable=True),
    sa.Column('firma_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('firma_ip', sa.String(length=45), nullable=True),
    sa.Column('firma_user_agent', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elaborador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estado_actual_id'], ['estados.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['firma_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gerencia_id'], ['gerencias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_flujo_activo'), 'documento_flujo', ['activo'], unique=False)
    op.create_index(op.f('ix_documento_flujo_documento_id'), 'documento_flujo', ['documento_id'], unique=False)
    op.create_index(op.f('ix_documento_flujo_estado_actual_id'), 'documento_flujo', ['estado_actual_id'], unique=False)
    op.create_index(op.f('ix_documento_flujo_tipo_solicitud'), 'documento_flujo', ['tipo_solicitud'], unique=False)
    op.create_index('ix_flujo_documento_estado', 'documento_flujo', ['documento_id', 'estado_actual_id'], unique=False)
    op.create_index('ix_flujo_tipo_solicitud_fecha', 'documento_flujo', ['tipo_solicitud', 'fecha_solicitud'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flujo_tipo_solicitud_fecha', table_name='documento_flujo')
    op.drop_index('ix_flujo_documento_estado', table_name='documento_flujo')
    op.drop_index(op.f('ix_documento_flujo_tipo_solicitud'), table_name='documento_flujo')
    op.drop_index(op.f('ix_documento_flujo_estado_actual_id'), table_name='documento_flujo')
    op.drop_index(op.f('ix_documento_flujo_documento_id'), table_name='documento_flujo')
    op.drop_index(op.f('ix_documento_flujo_activo'), table_name='documento_flujo')
    op.drop_table('documento_flujo')
    op.drop_index(op.f('ix_archivos_adjuntos_documento_id'), table_name='archivos_adjuntos')
    op.drop_index('ix_archivo_documento_tipo', table_name='archivos_adjuntos')
    op.drop_table('archivos_adjuntos')
    op.drop_index(op.f('ix_documentos_vigencia'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_tipo_documento_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_proceso_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_gerencia_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_expira_at'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_estatus'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_codigo_antiguo'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_codigo'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_area_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_aprobacion_at'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_activo'), table_name='documentos')
    op.drop_index('ix_documento_vigencia_expira', table_name='documentos')
    op.drop_index('ix_documento_estatus_activo', table_name='documentos')
    op.drop_index('ix_documento_area_tipo', table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
